baseurl = "https://yokingco.github.io/"
title = "Amanda Yokingco"
author = "Amanda Yokingco"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

enableEmoji = true
hasCJKLanguage = false

pygmentsstyle = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
  sitename = "Amanda Yokingco"
  faviconfile = "images/favicon.png"
  highlightjs = true
  highlightjslanguages = ["r", "python", "stan"]
  uselatex = true
  progressively = false
# commentsrepo = "user/repo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.primary]]
    name = "Blog"
    url = "/"
    weight = 1
[[menu.primary]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.primary]]
    name = "GitHub"
    url = "https://github.com/yokingco/"
    weight = 3
[[menu.primary]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/amanda-yokingco/"
    weight = 4
[[menu.primary]]
    name = "Contact"
    url = "mailto:amanda.yokingco@mail.utoronto.ca"
    weight = 5
